title: CP F 2024
theme: jekyll-theme-minimal
days:
- title: Day 1 (2nd of March)
  url: day1.html
- title: Day 2 (16th of March)
  url: day2.html
- title: Day 3 (6th of April)
  url: day3.html
- title: Day 4 (13th of April)
  url: day4.html
- title: Day 5 (27th of April)
  url: day5.html
- title: Day 6 (26th of May)
  url: day6.html
- title: Midterm 2023 solutions
  url: midterm2023fall.html
- title: Exam 2023 solutions
  url: exam2023fall.html


